controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hello_page:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: "hello_page.html.twig"
